// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication3.Models
{
    public partial class Attempt
    {
        public int AttemptId { get; set; }
        public string ClientId { get; set; }
        public int RecipeId { get; set; }
        public string ConfigLink { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }

        public virtual ClientRecipe ClientRecipe { get; set; }
    }
}