// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication3.Models
{
    public partial class Client
    {
        public Client()
        {
            ClientRecipes = new HashSet<ClientRecipe>();
            Samples = new HashSet<Sample>();
        }

        public int ClientId { get; set; }
        public string Email { get; set; }

        public virtual ICollection<ClientRecipe> ClientRecipes { get; set; }
        public virtual ICollection<Sample> Samples { get; set; }
    }
}