// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication3.Models
{
    public partial class Picture
    {
        public int PictureId { get; set; }
        public int RecipeId { get; set; }
        public string Link { get; set; }

        public virtual Recipe Recipe { get; set; }
    }
}