// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication3.Models
{
    public partial class Recipe
    {
        public Recipe()
        {
            ClientRecipes = new HashSet<ClientRecipe>();
            Pictures = new HashSet<Picture>();
        }

        public int RecipeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ConfigLink { get; set; }
        public byte Abv { get; set; }
        public byte Ibu { get; set; }
        public byte Og { get; set; }
        public byte Fg { get; set; }
        public byte Ba { get; set; }
        public decimal Price { get; set; }

        public virtual ICollection<ClientRecipe> ClientRecipes { get; set; }
        public virtual ICollection<Picture> Pictures { get; set; }
    }
}